import matplotlib.pyplot as plt
import numpy as np
AverageWaitingTimes = np.array([0.00105, 0.08014, 0.17407, 0.221615, 0.252145])
WorstWaitingTimes = np.array([0.002, 3.22, 4.626, 10.593, 12.451])
numberOfPhilosophers = np.array([1, 5, 10, 15, 20])
plt.plot(numberOfPhilosophers, WorstWaitingTimes, label="Worst Waiting Time")
plt.plot(numberOfPhilosophers, AverageWaitingTimes, label="Average Waiting Time")
plt.grid()
plt.legend()
plt.xlabel('Number of Philosophers')
plt.ylabel('Time (ms)')
plt.savefig('./graph.eps', format = 'eps', dpi = 1000)
# plt.clf()
# plt.plot(prod_cons_ratio, lock_consumer, label="Lock")
# plt.plot(prod_cons_ratio, semaphore_consumer, label="Semaphore")
# plt.grid()
# plt.legend()
# plt.xlabel('Up/Uc')
# plt.ylabel('Average Waiting Time')
# plt.savefig('./consumer.eps', format = 'eps', dpi = 1000)
